version: "3.1"

services:
  kavanest-client:
    container_name: kavanest-client
    image: kavanest-client
    build:
      context: .
      dockerfile: Dockerfile.local
    networks:
      - proxynet
    environment:
      - REACT_APP_API_DOCKER="https://localhost:4000/"
    ports:
      - 80:80

networks:
  proxynet:
    name: kavanest-devnet
