## Build
FROM node:14 as build

# Set working directory
WORKDIR /app

# Add node_modules.bin to path
ENV PATH /app/node_modules.bin:$PATH
ENV VITE_API https://test.api.kavanet.io/
ENV VITE_SOCKET https://test.socket.kavanet.io/

# Copy package.json & package-lock.json to container
COPY package*.json ./

# Install dependencies
RUN yarn install

# Copy all (not listed in .dockerignore) to container
COPY . ./

# Build app
RUN yarn build


## Production
FROM --platform=linux/arm64 arm64v8/nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]

###
FROM node:20-alpine as builder
WORKDIR /app
COPY . .
ARG VITE_APP_BACKEND_ADDRESS
ENV VITE_APP_BACKEND_ADDRESS $VITE_APP_BACKEND_ADDRESS
RUN npm install
RUN npm run build

FROM nginx:1.25.4-alpine-slim as prod
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf  /etc/nginx/conf.d
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]