#* This commented out stuff uses an nginx config file, not sure its needed
# FROM arm64v8/nginx

# COPY build/ /usr/share/nginx/html

# COPY nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80

FROM arm64v8/nginx

COPY build/ /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]