# FROM arm64v8/nginx

# COPY build/ /usr/share/nginx/html

# COPY nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80

FROM arm64v8/nginx

# Copy contense of the build folder to nginex root
COPY build/ /usr/share/nginx/html

# Open port 80
# EXPOSE 80

# Start Nginx service
CMD ["nginx", "-g", "daemon off;"]