# Client docker doesnt work at the moment due to how react injects environment variables
# Need to create a seperate build step and inject them there
version: "3.1"
services:
  kavanest-client:
    container_name: kavanest-client
    image: kavanest-client
    build:
      context: .
      dockerfile: Dockerfile.argo
    networks:
      - proxynet
    environment:
      - REACT_APP_API="https://localhost:4000/"
      - REACT_APP_SOCKET="https://socket.kavanet.io/"
    ports:
      - 80:80

networks:
  proxynet:
    name: kavanest-devnet
