name: kavanest-client

namespace: kavanest
env:
  APP_VERSION: 52601d286740bb5ae0e86f135be590f28b25536a

deployment:
  - name: kavanest-client
    image: invisibug/kavanest-client
    ports:
    - port: 80
    # env:
      # Handled in Dockerfile.live

ingress:
  - name: client.kavanet.io
    selector: kavanest-client
    path: /.*
    port: 80
    host: client.kavanet.io

  - name: a.kavanet.io
    selector: kavanest-client
    path: /.*
    port: 80
    host: a.kavanet.io

service:
  loadBalancer:
    - name: kavanest-client
      selector: kavanest-client
      port: 80
