name: kavanest-test-client

namespace: kavanest-test

deployment:
  - name: kavanest-test-client
    image: invisibug/kavanest-client:test
    ports:
    - port: 80
    # env:
      # Handled in Dockerfile.test

ingress:
  - name: test.client.kavanet.io
    selector: kavanest-test-client
    path: /
    port: 80
    host: test.client.kavanet.io

  - name: demo.kavanet.io
    selector: kavanest-test-client
    path: /
    port: 80
    host: demo.kavanet.io

service:
  loadBalancer:
    - name: kavanest-test-client
      selector: kavanest-test-client
      port: 80
