name: kavanest-test-client

namespace: kavanest-test

deployment:
  - name: kavanest-test-client
    image: 192.168.1.61:5000/kavanest-client
    ports:
    - port: 80
    # env:
      # Handled in Dockerfile.test

ingress:
  - name: test.client.kavanet.io
    selector: kavanest-test-client
    path: /
    port: 80
    host: test.client.kavanet.io

service:
  loadBalancer:
    - name: kavanest-test-client
      selector: kavanest-test-client
      port: 80
