name: kavanest-test-client

namespace: kavanest-test
env:
  APP_VERSION: afd180b68bb20fad53970b51bae7c7bacea964a1

deployment:
  - name: kavanest-test-client
    image: invisibug/kavanest-test-client
    ports:
    - port: 80
    # env:
      # Handled in Dockerfile.argo.test

ingress:
  - name: test.client.kavanet.io
    selector: kavanest-test-client
    path: /
    port: 80
    host: test.client.kavanet.io

  - name: demo.kavanet.io
    selector: kavanest-test-client
    path: /
    port: 80
    host: demo.kavanet.io

service:
  loadBalancer:
    - name: kavanest-test-client
      selector: kavanest-test-client
      port: 80
