export { default as Home } from "./home-notUsed";
export { Setpoints } from "./setpoints";
export { Plugs } from "./plugs-notUsed";
export { default as Sensors } from "./sensors/sensorsScreen";
export { RGBLightsScreen as RGBLights } from "./lights";
export { Computer } from "./computer";
export { Valves } from "./valves";
export { Bed } from "./bed";
export { default as Study } from "./rooms/study";
export { default as Bedroom } from "./rooms/bedroom";
export { default as Livingroom } from "./rooms/livingroom";
export { default as Kitchen } from "./rooms/kitchen";
